### ISSUE TITLE
Vulnerability in Lodash versions below < 4.17.11

### ISSUE THREAD

**Issue by sam-warren-finnair** [request/promise-core#13]
https://snyk.io/vuln/SNYK-JS-LODASH-73639

Is it possible to up the lodash version in package.json?

**Comment by analog-nico** [comment]
Thanks for reporting this @sam-warren-finnair ! I just released `request-promise@4.2.3`, `request-promise-native@1.0.6`, and `request-promise-any@1.0.6` which bump `lodash` to `@4.17.11`.

**Comment by sam-warren-finnair** [comment]
Fantastic, thanks so much for this!

**Comment by analog-nico** [comment]
My pleasure buddy. :)
