### ISSUE TITLE
lodash isFunction missing _baseGetTag

### ISSUE THREAD

**Issue by kutenai** [request/promise-core#22]
I'm getting an error in every single one of my tests due to missing file
var baseGetTag = require('./_baseGetTag'),

This is called from lodash/isFunction, which is embedded in this module. I'm not sure why this module "embeds" lodash, or how that gets messed up, but my debug output shows very little information... I tracked it down to this module at least, but I'm not sure why this is not an issue for this  module, bu an issue for me.

**Comment by analog-nico** [comment]
Where you able to resolve it? It may help to delete your `node_modules` folder and do a `npm install` from scratch. Something seems to be messed up with your installed packages. Feel free to reopen this issue if it persists.

**Comment by kutenai** [comment]
I was able to resolve this. This issue was unrelated to the error. The issue was caused by version conflicts with node and npm between nvm and homebrew. Once I cleaned up the installation environment, I was able to remove node_modules and reinstall with both npm and yarn without issues.

**Comment by analog-nico** [comment]
Excellent. Thanks for letting us know in case someone else has the same issue! Have a great Sunday @kutenai . :)
