### ISSUE TITLE
Lodash dependency causes prototype pollution issue: can you use another package instead of lodash?

### ISSUE THREAD

**Issue by marcoippolito** [request/promise-core#26]
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-service                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-service > @vue/cli-plugin-router >                  │
│               │ @vue/cli-shared-utils > request-promise-native >             │
│               │ request-promise-core > lodash                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1523     

https://www.npmjs.com/advisories/1523 : "No fix is currently available. Consider using an alternative package until a fix is made available."

request-promise-core@1.1.3

So... can you use another package instead of lodash?

Marco

**Comment by analog-nico** [comment]
Since the `request-promise` family has been deprecated alongside `request` I won’t do major changes anymore. Sorry. 

However, I just updated `lodash` to the latest version which mitigates the security vulnerability.
