### ISSUE TITLE
when using baseUrl errors only show path as url property.

### ISSUE THREAD

**Issue by kilianc** [request/promise-core#6]
I am not sure if this github issue should bubble up to `request` itself but whenever an error is raised with a request client defaulted with a baseUrl, the error message will only show the path instead of the full url, which makes it almost impossible to debug.

**Comment by analog-nico** [comment]
You are talking about using `rp.defaults({ baseUrl: ... })`, right? You may have a look at `err.options` but as far as I remember these options don’t contain the defaults. That said, `err.response` certainly has the full info. In particular, have a look at `err.response.req` which is the original request.
